### PR TITLE
fix: migrate subdomains to wallet key address

### LINKED ISSUE #1209: Enable users to transfer subdomains to wallet-key addresses that correspond to all data-key addresses
The CLI should allow the user to run a command that:

1. Detects whether there are any subdomains registered with the user's key and owned by data-key-derived addresses
2. Prompts the user to confirm whether they want to migrate these subdomains to the corresponding wallet-key-derived addresses for their key by position
3. Alerts the user to any subdomains that can't be migrated to these wallet-key-derived addresses given collision with existing usernames owned by them
4. Initiates request to subdomain registrar using [new transfer endpoint](https://github.com/stacks-network/subdomain-registrar/issues/79) upon confirmation
5. Displays message indicating how long the user will have to wait until request is likely fulfilled
6. Displays confirmation that no subdomains are pending migration if user tries to execute command again

### PR DESCRIPTION
**Pull request by ahsan-javaid**
## Description
Add command in cli to enable users to transfer subdomains to wallet-key addresses that correspond to all data-key addresses

Example: Running the command
```
stx migrate_subdomains "sound idle panel often situate develop unit text design antenna vendor screen opinion balcony share trigger accuse scatter visa uniform brass update opinion media"
```

For details refer to issue #1209

## Type of Change
- [X] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [ ] Other

## Does this introduce a breaking change?
No

## Are documentation updates required?
No

## Testing information

Provide context on how tests should be performed.
`cd packages/cli`
`npm run build`
`./bin.js migrate_subdomains "sound idle panel often situate develop unit text design antenna vendor screen opinion balcony share trigger accuse scatter visa uniform brass update opinion media"`

## Checklist
- [X] Code is commented where needed
- [ ] Unit test coverage for new or modified code paths
- [X] `npm run test` passes
- [ ] Changelog is updated
- [ ] Tag reviewers

### CODE REVIEW

**Comment by markmhendrickson** [comment]
@ahsan-javaid is this ready for testing? cc @pradel

**Comment by ahsan-javaid** [comment]
Update: 

- Working on to write tests (In progress)
- @asimm241 is developing the api on subdomain-registrar side (In progress)
----------------------------------------------------
However mock testing can be done on this PR
Steps:
1. Clone stacks.js and setup
2. checkout to branch `fix/subdomain-migration-to-wallet-addresses`
3. cd packages/cli
4. Now run the command below
5. ./bin.js migrate_subdomains "sound idle panel often situate develop unit text design antenna vendor screen opinion balcony share trigger accuse scatter visa uniform brass update opinion media"

This will trigger the subdomain migration flow but actually subdomain will not be migrated as the actual migration url needs to be added. 

----------------------------------------------------

I will provide the final update next week once its fully ready to test.


cc: @asimm241

**Comment by markmhendrickson** [comment]
@ahsan-javaid Is this ready to test by chance? And mind providing a link to the API work on the registrar?

**Comment by asimm241** [comment]
> @ahsan-javaid Is this ready to test by chance? And mind providing a link to the API work on the registrar?

@markmhx It will be ready by the end of this week.

**Comment by asimm241** [comment]
> @ahsan-javaid Is this ready to test by chance? And mind providing a link to the API work on the registrar?

I'll open up a PR today or tomorrow for the API registrar section.

**Comment by markmhendrickson** [comment]
@ahsan-javaid @asimm241 Any updates on this work? I've heard from @pradel that his users are now waiting eagerly for this functionality 🙏

**Comment by asimm241** [comment]
@markmhx This PR is ready, the corresponding PR in the registrar will probably be created today OR tomorrow. Then It can be tested.  The unite tests will be added later.  :)

File: packages/transactions/src/utils.ts [hunk 1]
```diff
@@ -10,6 +10,9 @@ import lodashCloneDeep from 'lodash.clonedeep';
 import { with0x } from '@stacks/common';
 import { bytesToHex } from '@noble/hashes/utils';
 
+// Export verify as utility method for signature verification
+export { verify } from '@noble/secp256k1';
```
Comment (janniks) [inline packages/transactions/src/utils.ts]:
```suggestion
export { verify as verifySignature } from '@noble/secp256k1';
```
can we rename this to make it more clear that a signature is being verified?

**Comment by asimm241** [comment]
Corresponding PR in registrar https://github.com/stacks-network/subdomain-registrar/pull/88

File: packages/cli/src/argparse.ts [hunk 2]
```diff
@@ -1380,6 +1380,33 @@ export const CLI_ARGS = {
         '\n',
       group: 'Key Management',
     },
+    migrate_subdomains: {
```
Comment (janniks) [inline packages/cli/src/argparse.ts:1383]: Could you add an optional `registrar` paramater (while defaulting to the current hardcoded value), similar to in [`register_subdomain`](https://docs.hiro.so/references/stacks-cli#register_subdomain) ? this would make the beta url easier to test: https://github.com/stacks-network/subdomain-registrar/pull/88#issuecomment-1154010940 and also allow users to use a custom registrar without rebuilding.

**Review by janniks — CHANGES_REQUESTED** [review]

**Comment by pradel** [comment]
@asimm241 @ahsan-javaid  Tested the latest commit of the pull request and no usernames were found.
It's a fresh account I created today using blockstack connect, it seams that usernames are not correctly detected.

Screenshot 2022-06-16 at 14 40 46

You can test with the seed phrase "tooth canyon empower leg duty piece reward foster shrimp rough lottery area" username registered is testmigrationsubdomain1.id.stx

**Comment by ahsan-javaid** [comment]
Yes no subdomains at this address:
```
curl https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP3RJTQCCX5RRJ381VS391F3X0N172HGZPJ5SARDR
```
Output:
{
  "names": []
}

**Comment by pradel** [comment]
Then it means usernames registered with blockstack connect are not registered under the dataPrivateKey but another one?

**Comment by pradel** [comment]
@ahsan-javaid to reproduce you can create a new legacy account by going to https://app.sigle.io/ and clicking "Blockstack connect", you will see the address of the dataPrivateKey is not the one owning the address. I don't know which derivation path uses Blockstack connect to register the username

**Comment by friedger** [comment]
@pradel The username is owned by the address that belongs to the "compressed public key". The code below shows both the address of the compressed and uncompressed public key: 
```
SP2472PRQ8QGW7RAHBYXV40112XX914RDR8AB3N3A
SP2472PRQ8QGW7RAHBYXV40112XX914RDR8AB3N3A SP3RJTQCCX5RRJ381VS391F3X0N172HGZPJ5SARDR
```

The public key was also generated via https://iancoleman.io/bip39/ in the bip32 tab using `m/888'/0'` with checked `Use hardened addresses` for the derived addresses.

```
import {
  addressFromPublicKeys,
  AddressVersion,
  compressPublicKey,
  createStacksPrivateKey,
  createStacksPublicKey,
  cvToHex,
  cvToString,
  deserializeTransaction,
  getAddressFromPrivateKey,
  getPublicKey,
  hexToCV,
  publicKeyToAddress,
  publicKeyToString,
  serializePayload,
  StacksPrivateKey,
  standardPrincipalCV,
  tupleCV,
} from "@stacks/transactions";

console.log(
  publicKeyToAddress(
    AddressVersion.MainnetSingleSig,
    createStacksPublicKey(
      "022dc8bf2b1a91479388518fff61d920aef6fce71661c590e6aa8341f4ca13e756"
    )
  )
);
generateWallet({
  secretKey:
    "tooth canyon empower leg duty piece reward foster shrimp rough lottery area",
  password: "abc",
}).then((r) => {
  console.log(
    publicKeyToAddress(
      AddressVersion.MainnetSingleSig,
      compressPublicKey(
        publicKeyToString(
          getPublicKey(createStacksPrivateKey(r.accounts[0].dataPrivateKey))
        )
      )
    ),
    publicKeyToAddress(
      AddressVersion.MainnetSingleSig,
      getPublicKey(createStacksPrivateKey(r.accounts[0].dataPrivateKey))
    )
  );
});

```

**Comment by friedger** [comment]
Or simplified: 
```js
  console.log(getAddressFromPrivateKey(r.accounts[0].dataPrivateKey)) // -> SP2472P..
  console.log(getAddressFromPrivateKey(r.accounts[0].dataPrivateKey + "01")) // -> SP3RJTQ..
```
**Update**: These are the correct addresses
```js
  console.log(getAddressFromPrivateKey(r.accounts[0].dataPrivateKey)) // -> SP3RJTQ..
  console.log(getAddressFromPrivateKey(r.accounts[0].dataPrivateKey + "01")) // -> SP2472P..
```

**Comment by friedger** [comment]
Converting the user's identity address `1DSShC11JJ1v9dvDCmBVx63MSzA4Kmbyjm` (based on the data private key) the address `SP2472PRQ8QGW7RAHBYXV40112XX914RDR8AB3N3A` should be the correct address that needs to be checked for names @ahsan-javaid

**Comment by janniks** [comment]
I'll take over and configure to the correct address.

Is there a spec (e.g. SIP-style) for which address (compressed/uncompressed) should be used for what (e.g. identity/usernames)? We should try to avoid "locking out" users if this is inconsistent (even if the lock-out would be recoverable by seed / CLI commands). CC @kantai @zone117x

**Comment by janniks** [comment]
> Or simplified:
> 
> ```js
>   console.log(getAddressFromPrivateKey(r.accounts[0].dataPrivateKey)) // -> SP2472P..
>   console.log(getAddressFromPrivateKey(r.accounts[0].dataPrivateKey + "01")) // -> SP3RJTQ..
> ```

It's the other way around, correct? (Or am I going crazy?)
`getAddressFromPrivateKey(r.accounts[0].dataPrivateKey + "01") → SP2472PRQ8QGW7RAHBYXV40112XX914RDR8AB3N3A`

**Comment by friedger** [comment]
@janniks you are right and not crazy

**Review by janniks — APPROVED** [review]

**Comment by janniks** [comment]
The migration now checks both compressed and uncompressed address versions. I will test with the live beta registrar tomorrow.

UPDATE: I added some data on the beta registrar, will test a migration on Friday.

**Comment by janniks** [comment]
I've made some progress. Finally.
It's not all roses 🌷 so I want to check with @kantai what the expected behavior is.

---

But, @pradel you should be able to test on the beta registrar:
```bash
npm install @stacks/cli@4.3.1-pr.13dc5b7.0 -g
stx migrate_subdomains "tissue ... silver" https://registrar-beta.stacks.co
```
_I'll send the full seed on discord._ 📬

**Comment by pradel** [comment]
@janniks just tested and it worked 🚀 
When I enter the seed in the Hiro wallet after the transfer is done I can see the name being displayed.

**Comment by pradel** [comment]
@janniks this function will allow legacy users to migrate their usernames to the Hiro wallet.

But what about transferring subdomains for Hiro wallet users, should stacks.js export a function that does this?

**Comment by unclemantis** [comment]
Would like to see a detailed markdown of exactly the issue being solved. I am a little confused. 👍

**Comment by janniks** [comment]
> @janniks this function will allow legacy users to migrate their usernames to the Hiro wallet.
> 
> But what about transferring subdomains for Hiro wallet users, should stacks.js export a function that does this?

That's a good point. I think they should be separate command though. For example, I would keep `migrate_subdomain` as the "fix" of legacy ids and add another command `transfer_subdomain` for the ability to send the subdomain to whoever (by address).
Thoughts?

**Comment by janniks** [comment]
> Would like to see a detailed markdown of exactly the issue being solved. I am a little confused. 👍

👍 I can add some more detail to the command descriptions. In short, the old Blockstack connect username where owned by a different derivation path of (data private key) of wallets, rather than the wallet key, which the web wallet uses now to own usernames. This command will migrate the address from the old to the current.

**Comment by pradel** [comment]
> That's a good point. I think they should be separate command though. For example, I would keep migrate_subdomain as the "fix" of legacy ids and add another command transfer_subdomain for the ability to send the subdomain to whoever (by address).
Thoughts?

Seems like a good approach 👍

**Comment by pradel** [comment]
@janniks created a separate issue for this https://github.com/hirosystems/stacks.js/issues/1323

**Comment by pradel** [comment]
@janniks wondering what is missing for this one (and the subdomain pr) to go live, our users are eagerly waiting 🤓

**Comment by saralab** [comment]
@zone117x : We are awaiting your review, can you take a peek please?

**Review by zone117x — APPROVED** [review]
The code and tests look good. But I haven't tested this out myself. If the folks testing this change are happy then LGTM.

**Comment by janniks** [comment]
✅ Ran final tests, we're just waiting for https://github.com/stacks-network/subdomain-registrar/pull/88 to be merged (I don't have access), then we can merge this PR.

**Comment by janniks** [comment]
📦 Released under `4.3.4`
