### PR TITLE
Better error responses

### LINKED ISSUE #436: Error handling: improve when decryption fails
We need better error handling when decryption fails (e.g., if the file wasn't encrypted in the first place).

This has been experienced more frequently since the upgrade where we switched to encrypt-by-default (see issue #434).

### LINKED ISSUE #601: getFile not rejecting the Promise
[Blockstack docs (`18.2.0`)](http://blockstack.github.io/blockstack.js/#getfile) states that `getFile` :

> resolves to the raw data in the file or rejects with an error

Nevertheless in practice it does resolve the `Promise` and returns a `null` object instead, thus never getting into the `.catch(` statement.

Even the DEBUG log says it so:
> [DEBUG] getFile my/file.json returned 404, returning null

### LINKED ISSUE #665: putFile(), deleteFile(), and listFiles() need to return the HTTP status on error
Because a POST can fail due to rate-limiting or authentication or other errors, the error paths for these methods should at the very least report the specific HTTP error encountered. Right now, only a generic exception is thrown.

### PR DESCRIPTION
**Pull request by shreyasthiagaraj**
As a Blockstack developer I'd like to get better error codes when operations fail. This PR implements https://github.com/blockstack/blockstack.js/pull/442 in Typescript as a starting point.

- Fixes #436 with a DecryptionFailedError
- Adds a proper ERROR_CODE to all instances of BlockstackException
- #413 by adding a URL to exception messages with a pre-filled URL that points to blockstack.org/bugs with some HTTP parameters that auto-fill the bug form.
- Fixes #665 by returning HTTP response code + error description for storage methods.
- Includes json/string information returned from Gaia in error responses.
- Fixes #601 by returning error instead of null when file is not found.

### CODE REVIEW

**Comment by moxiegirl** [comment]
@shreyasthiagaraj I believe @timstackblock  wants the bugs filed in GitHub not the forum --- which is where your PR is going to send them. Tim, I may have misunderstood you.

**Comment by shreyasthiagaraj** [comment]
@moxiegirl I don't understand. My PR will send bugs to the forum?

**Comment by moxiegirl** [comment]
> @moxiegirl I don't understand. My PR will send bugs to the forum?

Yes, @shreyasthiagaraj . if you take the link you refer to in the description (`blockstack.org/bugs`) and in the code, the link redirects to this: https://forum.blockstack.org  which is the forum.

File: src/storage/hub.ts [hunk 1]
```diff
@@ -51,7 +52,8 @@ export async function uploadToGaiaHub(
     }
   )
   if (!response.ok) {
-    throw new Error('Error when uploading to Gaia hub')
+    const responseDescription = await getResponseDescription(response)
```
Comment (zone117x) [inline src/storage/hub.ts]: I know this is still on your PR TODO list -- but here is the list of Gaia hub upload error responses: https://github.com/blockstack/gaia/blob/ff1cd245e4df7244e8c6e32f08e95ec2aba9834e/hub/src/server/http.ts#L68-L79

I think we will probably want corresponding error codes and class types that match those.

File: src/errors.ts [hunk 2]
```diff
@@ -32,8 +39,22 @@ export class BlockstackError extends Error {
   parameter?: string
 
   constructor(error: ErrorType) {
-    super(error.message)
-    this.message = error.message
+    let message = error.message
+    let bugMessage = `Error Code: ${error.code}`
+    let stack = null
```
Comment (zone117x) [inline src/errors.ts]: `Error.stack` is [weird](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack). Depending on the runtime, I think typically `this.stack` will already be set, and closer to the offending lines.

It might be better for this code to look something like 
```js
let stack = this.stack
if (!stack) { 
  try {
    throw new Error()
  } catch (e) {
     stack = e.stack
  }
}
```

File: src/encryption/ec.ts [hunk 3]
```diff
@@ -3,6 +3,7 @@ import { ec as EllipticCurve } from 'elliptic'
 // @ts-ignore
 import * as BN from 'bn.js'
 import * as crypto from 'crypto'
+import { FailedDecryptionError } from './errors'
```
Comment (zone117x) [inline src/encryption/ec.ts]: Looks like this is failing tests. I think it needs to be 
```ts
import { FailedDecryptionError } from '../errors'
```

**Review by zone117x — CHANGES_REQUESTED** [review]
Looking good so far! I left some comments for potential changes & fixes

File: src/errors.ts (hunk 2 above)
Comment (shreyasthiagaraj) [reply src/errors.ts]: Unfortunately `this.stack` is inaccessible until I do `super(message)`, where `message` requires the stack :-/.

File: src/encryption/ec.ts (hunk 3 above)
Comment (shreyasthiagaraj) [reply src/encryption/ec.ts]: Oops, fixed 👍

File: src/storage/hub.ts (hunk 1 above)
Comment (shreyasthiagaraj) [reply src/storage/hub.ts]: Done 👍

File: src/errors.ts (hunk 2 above)
Comment (zone117x) [reply src/errors.ts]: You should be able to call `super(error.message)` or just `super()` at the beginning of the constructor and the later `this.message` reassignment should work as intended

File: src/storage/hub.ts (hunk 1 above)
Comment (zone117x) [reply src/storage/hub.ts]: Looking good! Couple minor change requests:
* The Gaia has a [`413 PayloadTooLarge`](https://github.com/blockstack/gaia/blob/ef0771833cd56200e08e18631e62467f24e086af/hub/src/server/http.ts#L78) error code _(it was recently introduced, you didn't miss it)_. 
* The [`delete` file endpoint](https://github.com/blockstack/gaia/blob/ef0771833cd56200e08e18631e62467f24e086af/hub/src/server/http.ts#L120-L131) can also return many of these same errors, in addition to a [specific 404 error](https://github.com/blockstack/gaia/blob/ef0771833cd56200e08e18631e62467f24e086af/hub/src/server/http.ts#L127). The blockstack.js function for that is located right underneath this one, see `function deleteFromGaiaHub`.. 
* Same thing for the [`list-files` endpoint](https://github.com/blockstack/gaia/blob/ef0771833cd56200e08e18631e62467f24e086af/hub/src/server/http.ts#L172). See `function listFilesLoop`.. which is in `src/storage/index.ts`.

All these fetch requests to the Gaia server should probably use a common error handling function, i.e. all `fetch` requests involving `GaiaHubConfig.server`.

**Review by zone117x — CHANGES_REQUESTED** [review]

File: src/storage/hub.ts [hunk 4]
```diff
@@ -51,8 +51,20 @@ export async function uploadToGaiaHub(
     }
   )
   if (!response.ok) {
-    throw new Error('Error when uploading to Gaia hub')
-  } 
+    const responseDescription = await getResponseDescription(response)
+    const errorMsg = `Error when uploading to Gaia hub. ${responseDescription}`
```
Comment (zone117x) [inline src/storage/hub.ts]: Gaia returns useful JSON error payloads for many error conditions. The function that provides this `responseDescription` value uses `response.text()`, so the `Error` object thrown will have a message string with embedded stringified json. This makes it hard for blockstack.js and apps to perform condition-specific error handling. 

It would be useful if these Gaia response errors contained the hub error response data. For example, the errors could extend something like:
```ts
interface GaiaHubErrorResponse {
  status: number, 
  statusText: string,
  body?: string | any
}

class GaiaHubError extends BlockstackError {
  hubError: {
    message?: string
    error?: string
    statusCode: number
    statusText: string
    [prop: string]: any
  }

  constructor(error: ErrorType, response: GaiaHubErrorResponse) {
    super(error)
    this.hubError = {
      statusCode: response.status,
      statusText: response.statusText
    }
    if (typeof response.body === 'string') {
      this.hubError.message = response.body
    } else if (typeof response.body === 'object') {
      Object.assign(this.hubError, response.body)
    }
  }
}
```

The `getResponseDescription` function could return the JSON if available, something like:
```ts
async function getGaiaErrorResponse(response: Response): Promise<GaiaHubErrorResponse> {
  let responseMsg = ''
  let responseJson: any | undefined
  try {
    responseMsg = await response.text()
    try {
      responseJson = JSON.parse(responseMsg)
    } catch (error) { 
      // ignore... server did not return JSON, use string response
    }
  } catch (error) {
    Logger.debug(`Error getting bad http response text: ${error}`)
  }
  return {
    status: response.status,
    statusText: response.statusText,
    body: responseJson || responseMsg
  }
}
```

File: src/errors.ts (hunk 2 above)
Comment (shreyasthiagaraj) [reply src/errors.ts]: Good idea. Done :).###

File: src/storage/hub.ts (hunk 4 above)
Comment (shreyasthiagaraj) [reply src/storage/hub.ts]: Done! Implemented changes based on your suggestions. Thanks!

Comment (shreyasthiagaraj) [reply src/storage/hub.ts]: `getBlockstackErrorFromResponse` in `utils.ts` is the central place to process gaia hub errors.

File: src/storage/hub.ts (hunk 1 above)
Comment (shreyasthiagaraj) [reply src/storage/hub.ts]: Done--`getBlockstackErrorFromResponse` in utils.ts is the central place to process gaia hub errors. Thanks!

**Comment by shreyasthiagaraj** [comment]
Hey!

**Comment by shreyasthiagaraj** [comment]
@zone117x I fixed 1 test that was obviously the result of my changes, but there are 10 more falling that seem totally unrelated. Is this a known issue, or should all tests currently be passing? Thanks!

File: src/storage/hub.ts [hunk 5]
```diff
@@ -72,20 +74,7 @@ export async function deleteFromGaiaHub(
...
-    }
-    const errorMsg = 'Error deleting file from Gaia hub: '
-      + `${response.status} ${response.statusText}: ${responseMsg}`
-    Logger.error(errorMsg)
-    if (response.status === 404) {
-      throw new FileNotFound(errorMsg)
-    } else {
-      throw new Error(errorMsg)
-    }
+    throw getBlockstackErrorFromResponse(response, 'Error deleting file from Gaia hub.')
```
Comment (zone117x) [inline src/storage/hub.ts]: I think this needs an `await`

**Review by zone117x — CHANGES_REQUESTED** [review]

File: src/storage/hub.ts (hunk 5 above)
Comment (zone117x) [reply src/storage/hub.ts]: That may explain some of the failing tests, a few `UnhandledPromiseRejectionWarning: Unhandled promise rejection` warnings in the logs.

Comment (shreyasthiagaraj) [reply src/storage/hub.ts]: Looking closer at the failures I found that there was 1 failure caused by my change to `getFile` behavior (missing files throw `DoesNotExist` error instead of returning null), and the rest were failing because that one failed. Once I fixed this test the rest all started passing 😀.

**Comment by shreyasthiagaraj** [comment]
Fixed all failing tests, and modified the `getFile throw on 404` test to check some of the values that the newly introduced `GaiaHubError` should contain. Let me know if it looks good, thanks!

File: src/storage/index.ts [hunk 6]
```diff
@@ -230,34 +230,25 @@ export async function getFileUrl(
...
-        return response.text()
-      } else {
-        return response.arrayBuffer()
-      }
-    })
+async function getFileContents(path: string, app: string, username: string | undefined, 
+                               zoneFileLookupURL: string | undefined,
+                               forceText: boolean,
+                               caller?: UserSession): Promise<string | ArrayBuffer | null> {
+  await Promise.resolve()
```
Comment (zone117x) [inline src/storage/index.ts]: This line can be removed, now that the function is marked `async` it is implicitly wrapped in a `Promise.resolve`

**Comment by zone117x** [comment]
This looks great! We should note in the changelog of breaking change: `getFile` throws error on 404 rather than returning null.

Adding @timstackblock as reviewer to perform the regular smoke tests. 

We should also test something like `getFile('bogus123_not_exists')` results in a useful console log message.

**Review by zone117x — APPROVED** [review]
Left a last comment where a line of code can be removed. Other than that, code looks good.

**Review by timstackblock — APPROVED** [review]

**Review by yknl — APPROVED** [review]
This looks good to me 👍
