### PR TITLE
fix: reduce fallbacks/polyfills

### LINKED ISSUE #1259: [stacking] Offload `bitcoinjs-lib`
replace bitcoinjs-lib in @stacks/stacking with secp/noble alternatives as in previous PRs

### PR DESCRIPTION
**Pull request by janniks**
- closes https://github.com/hirosystems/stacks.js/issues/1259
- reduces unnecessary polyfilling

### CODE REVIEW

File: packages/encryption/src/messageSignature.ts [hunk 1]
```diff
@@ -1,13 +1,13 @@
-import { sha256 } from 'sha.js';
-import { encode, decode, encodingLength } from 'varuint-bitcoin';
+import { sha256 } from '@noble/hashes/sha256';
```
Comment (zone117x) [inline packages/encryption/src/messageSignature.ts:1]: Is the `sha.js` dep still used? It's still in package.json

File: packages/transactions/src/utils.ts [hunk 2]
```diff
@@ -66,7 +68,8 @@ export function omit<T, K extends keyof any>(obj: T, prop: K): Omit<T, K> {
   return clone;
 }
 
-export class sha512_256 extends sha512 {
+/** @deprecated use @noble/hashes instead */
+export class sha512_256 extends shaJsSha512 {
```
Comment (zone117x) [inline packages/transactions/src/utils.ts]: Any compelling reason to deprecate this instead of just removing it?

File: packages/encryption/src/messageSignature.ts [hunk 3]
```diff
@@ -1,13 +1,13 @@
...
 import { Buffer } from '@stacks/common';
+import { decode, encode, encodingLength } from 'varuint-bitcoin';
```
Comment (zone117x) [inline packages/encryption/src/messageSignature.ts:3]: Note: `varuint-bitcoin` is a good candidate for vendoring later, it has an unfriendly Nodejs buffer polyfill dependency.

**Review by zone117x — APPROVED** [review]

File: packages/encryption/src/messageSignature.ts (hunk 1 above)
Comment (janniks) [reply packages/encryption/src/messageSignature.ts:1]: Nope, was intended to be removed — I missed it, thanks 🙏

File: packages/transactions/src/utils.ts (hunk 2 above)
Comment (janniks) [reply packages/transactions/src/utils.ts]: I'd be happy to remove and treat it as an internal (not triggering breaking change). Otherwise if we want to treat as external and used by consumers, I would keep this change to a minor/patch and remove the deprecated with the next major release.

But honestly, it's unlikely folks used this undocumented helper, even if it was `export`ed, so I'd also prefer treating this (and similar methods) as internal.
